import { CategoryCont } from "@/components/CategoryCont";
import { Layout } from "@/components/Layout";
import { MiddleEast } from "@/components/MiddleEast";
import { TopSection } from "@/components/TopSection";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Asian Chronicles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <TopSection />
        <MiddleEast />
        <CategoryCont />
      </Layout>
    </>
  );
}
